### PR TITLE
add toolbar and contextual menu

### PR DESCRIPTION
**Pull request by oroulet**
this is a draft, working but may need some polishing. Maybe an option for people who do not want toolbar, and larger icons. Where do the icon come from? can't we use svg icons?

### CODE REVIEW

**Comment by kmicc** [comment]
Hello and thank you for your contribution. I've just tested it out and I found two issues. The first one is clearly NOT your fault, but anyway: The used icons are just too similar, see icons for "Create New Task" and "Increase Priority" on the one side, and the icons for "Delete task" and "Decrease Priority" on the other side. I know exactly these icons are also used in the main menu, but there is additional text to them. As standalone, this iconset is imho a no-go. Sorry :-(

The second issue is not that import. You choose "Edit" as the name for the toolbar. That's ok, but that name is shown in the contextual menu of the main menu and the toolbar. I would suggest to use "Show toolbar" instead, to make the contextual menu self explanatory.

**Comment by oroulet** [comment]
Added contextual menu, This works fine, but maybe, the menu should only appear when a task is selected (easy) and not show "Create New Action" when an item is selected (I do not know how but should not be hard)

**Comment by oroulet** [comment]
use custom contextual menu. Now it behave as it should. We could even show a different menu when no task is selected, but I do not think this is necessary.
I know the icons should be fixed but I will not do it until the patch is accepted or a fork is decided

**Comment by kmicc** [comment]
The contextual menu works fine! I've just merged it into https://github.com/kmicc/QTodoTxt. I think the "Create New Task" is quite handy, even or especially when clicking on existing tasks, so I've choosen that version of the contextual menu.

I would also have merged your toolbar, but I don't want to click accidentally on the "Delete"-Button, when I just want to decrease the priority, so I didn't. But this was the only reason!

Well, I actually don't want to fork this repository. But I also don't want to wait until something happens here. QTodoTxt is a quite good project, but it needs improvement. I'm going to implement some features in my own repository, that I personally want to have. I'm also going to include useful code from other people, for example code from existing pull requests. If nothing else happens here, I'm willing to push forward this project at least to a new release.

**Comment by oroulet** [comment]
@funkyfuture what is your current stand point on toolbar and contextual menu?
 I see some people want to fork but I think the best thing would be agree all on a compromise, create a github group and work from there. But for that to happen we need a common vision and a hope that will merge your work soon.
I want toolbar and contextual menu. the necessary code is very short so it should be possible to agree on a solution with, for example a settings for visible toolbar

**Comment by funkyfuture** [comment]
imo the most notable design paradigm is to have a very minimalistic UI.

so, please make this a configurable opt-in.
feel free to refactor the settings code to something reasonable on that occasion. ;-) (i'd like to see the settings stored as JSON.)

**Comment by oroulet** [comment]
The program is written in qt. The most sensible thing is to use qsettings
for setting and not re invent the wheel...
Btw settings to enable or disable contextual menu sounds a bit stupid. Menu
is not visible until user explicitly ask for it...

**Comment by kmicc** [comment]
An opt-out for the toolbar is already implemented (just do a right mouse click on the toolbar or the menu), but not persistent when restarting the application. An opt-in / opt-out for the context menu doesn't make sense for me. I don't see an urgent need to refactor the settings code (but I didn't looked deeper into it), but if one want to do this, using qsettings would be also my first choice.

**Comment by oroulet** [comment]
Added settings and new icons. I am absolutely not an artist, I just tok the first match on wikimedia.org. 
Is this acceptable patch now?

**Comment by kmicc** [comment]
Thanks! I've just tested it and everything seems to work. We won't win a design award with these icons, but they will do the job.

Some minor suggestions (but these won't be show stoppers):
- I personally would prefer a contextual menu WITH a "Create New Task"-entry. (I would furthermore suggest to add an "Edit Task"-entry to the edit-main menu, the toolbar and the contextual menu.)
- I think it is really cool that one can move the toolbar around and can dock it to an arbritrary side of the window. It would be superb if the choosen position would be saved. 
- Would it be possible to add some separation lines to the contextual menu, the tool bar and the edit-main menu?

One thing I don't like: The use of QSettings while there is still the .cfg file. QSettings should be the future, but using both methods at the same time seems not to be a good idea. Maybe you want to take a look at https://github.com/kmicc/QTodoTxt/commit/ee6c99e3a1016c497a7a3397a3fabba5df3d44cb - using the existing .cfg should not be too difficult.

**Comment by oroulet** [comment]
>
>    - I personally would prefer a contextual menu WITH a "Create New
>    Task"-entry.
>
> I vote against that one. contextual menu os about context. and create new
task has nothing to do with the current task. But we could show that action
if not task is selected?


>
>    - (I would furthermore suggest to add an "Edit Task"-entry to the
>    edit-main menu, the toolbar and the contextual menu.)
>
> It makes sense


>
>    - I think it is really cool that one can move the toolbar around and
>    can dock it to an arbritrary side of the window. It would be superb if the
>    choosen position would be saved.
>
>
next patch

>
>    - Would it be possible to add some separation lines to the contextual
>    menu, the tool bar and the edit-main menu?
>
>
yea easy but where? if you have ideas you should do it

>
>
> One thing I don't like: The use of QSettings while there is still the .cfg
> file. QSettings
>

I did not see that cfg stuff before you pointed at it. Having a custom cfg
file seems a like strange idea for a Qt application, and probably breaks in
many situations..... I think using qsettings is the correct method. I
propose to let the qsettings think in this patch then someone can create a
new pull request to move all other settings to qsettings.
An advantage of QSettings is that you can create the QSetings object at
many places in the application. it does not matter and does not take any
extra memory.

**Comment by oroulet** [comment]
Can we merge this one? or is there any non-addressed concerns? This patch changes the interface so one should think a bit about it

**Comment by kmicc** [comment]
If you fixed the problem with the save button, you can merge (imho). I still have some minor issues, but I think it will be the best to create some new issues for them, so we can close this lengthy discussion and discuss them separatly.

**Comment by oroulet** [comment]
done. I think more work should be done in another pull request

**Comment by kmicc** [comment]
Ok.

**Pull request merged**
