### PR TITLE
Use QSettings

### PR DESCRIPTION
**Pull request by kmicc**
Spitted up from #187, implements #179.

### CODE REVIEW

**Comment by kmicc** [comment]
First of all: Thank you for adressing this issue. I've just get it managed to merge this with my daily used productive code, so please let this PR open for some more days for further testing because this change has a bigger impact.

**Comment by kmicc** [comment]
Here the issues I found up to now:
1. The "auto-save" option is saved as true/false instead of 1/0. After changing this option, the application doesn't start any more.
2. It doesn't save the position of the slider between the filter tree view and the task view.
3. If I switch the option "Hide future tasks", I have to restart the application for reflecting this in the taskview.
4. The timing of setting the position / size of the application window changed. With this PR, the application window is first shown, and 'then' resized and repositioned. That a) looks ugly and b) causes problems with the position of the line break of multiline task (currently linebreak is calculated only once on application startup, not after resizing).

Number 2-4 are not that bad as number 1, but I think they should be fixed too because they are clearly regressions from the previous version.

**Comment by oroulet** [comment]
OK I  will have a look

**Comment by oroulet** [comment]
cherry-pick this one https://github.com/oroulet/QTodoTxt/commit/c86dd847aa609d430fb09471bd0746c013fbcf83

It should fix, all your reported bugs, but test it since I do not use/see any of those feature

**Comment by kmicc** [comment]
Note: This PR will also close #116 and the not yet reported problem that QTodoTxt currently doesn't start without a ~/.qtodotxt.cfg (i.e. after installation, you will have to create such a file with e.g. minimal content "{}" - had that problem under windows, but can't reproduce under linux).

**Comment by kmicc** [comment]
* Application didn't start without an existing config file --> fixed.
* Number 2 and 4 are now ok, thank you.
* Number 1 and 3 are still not ok. Setting "Auto save" or "Hide future tasks" in the Gui simply has no effect. Not in the running application, not after restarting the application. The only way to change these options is manual editing the config file.

I will now dive deeper in your changes and take a look whats going wrong there.

And could you please push future changes concering these pull requests directly to the corresponding branches in this repository here? I didn't create all these branches for fun.

**Comment by kmicc** [comment]
I simplified some hardly understandable code. As a result, the options "Auto save" or "Hide future tasks" now work as expected. Now it is the "Add creation date" option which worked fine before that takes effect only after restarting the application. The "Auto Archive" Option is untested, e.g. may also fail.

**Comment by kmicc** [comment]
Found the error. Now everything should work as expected.

**Comment by kmicc** [comment]
I just found out that this pull request also solves #176 (save toolbar position).

**Comment by oroulet** [comment]
>> And could you please push future changes concering these pull requests directly to the corresponding branches in this repository here?

I did not see that you created the branches directly in main repository. It is not a good idea to work directly on main repository, it is very easy to do mistakes. Trust me, I have tried ... Work on your own repository clone, create branch there and create pull request. It is possible to create branch on main repository, but then they should be for a long term work were code is committed through pull request.

Concerning this pull request, I think you should merge all those small commits into one then merge to master. Otherwise we will get a lot of small commits that breaks code , and will make using tools like bisect impossible to use.

**Comment by oroulet** [comment]
otherwise the patch looks good for me

**Comment by kmicc** [comment]
You surely made experiences that I didn't made (yet), so I respect your position about branches in the main repository. But how should we work together on a single feature NOT using branches in the main repository? Creating a pull request on a branch in a cloned repository to add commits to a pull request in the main repository seems to be awkward to me, will create additional merge commits and scatters up discussions. I don't see any reasons against short-lived feature branches in the main repository.

**Comment by kmicc** [comment]
What is the tool bisect good for? Never used it.

**Comment by oroulet** [comment]
> But how should we work together on a single feature NOT using branches in the main repository? 

usually one author is master for a feature. If someone want to contribute he can either create a PR on the feature branch or send link to a commit and main author can fetch it:
git fetch https://github.com/QTodoTxt/QTodoTxt
git cherry-pick xxxxxx

git bisect is when a bug has happened and nobody knows where it comes from. git bisect will help to find out which commit is to blame, but it requires that every commit in tree is working and does not break completely the software

git rebase -i can used to easily merge commits together

**Comment by kmicc** [comment]
> usually one author is master for a feature. If someone want to contribute he can either create a PR on the feature branch or send link to a commit and main author can fetch it

I'm not 100% convicted but I will rely on this for future pull requests (the "fixing travis" branches are an exception, they have to be in the main repository due to the CI).

Regarding the number of commits: I prefer having exactly one logical change in one single commit, e.g. not mixing renaming some stuff and bugfixing some other stuff in the same commit. This results in a higher number of commits, but makes debugging and / or reverting single commits easier (imho). It's ok if you don't rely on this policy, but I'm not going to change mine.

One last thing: Can we please agree that in the future one pull request contains exactly one feature / bugfix / ... ? I really don't want to have the discussions from all of the 4 pull requests splitted up from #187 merged into one single thread!

**Comment by kmicc** [comment]
Regarding this PR: Can be merged imho. Your turn!

**Comment by oroulet** [comment]
merged a cleaned up version of this PR

**Comment by oroulet** [comment]
>> prefer having exactly one logical change in one single commit

agree

>>  I prefer having exactly one logical change in one single commit,

Did I say anything else?
But we donnot need to merge things like
first commit X
attempt 1 to fix commit X
attemp 2 to fix commit X
attemp 3 to fix commit 
etc...

btw, I see that you merged from master in your PR on top. I advice you to use "git pull -r" it makes a much cleaner history without dummy commit, etc, ...

**Comment by kmicc** [comment]
Thanks for the hint with "git pull -r". Will give it a try.

**Pull request closed without merging**
