### PR TITLE
Singleton

### PR DESCRIPTION
**Pull request by PKEv**
based on tendo lib, realized by mmap file and pyqtSignal

Implemented:
1.the uniqueness of the running script, provided start-up from one place
2.When you start second the focus transferred to the running application
3.also supports the transfer of the command line options (-q) but without closing the application

close: #76, #238

### CODE REVIEW

**Comment by oroulet** [comment]
Code looks OK . Was it tested on Linux and Windows? 
If the code was taken from another library, maybe you should document it in file?

**Comment by PKEv** [comment]
i can test only in windows

**Comment by PKEv** [comment]
I took a bite out of this library https://github.com/pycontribs/tendo
I have not found references to a license

**Comment by oroulet** [comment]
It seems to be broken on Linux.
* The preferences shows it is on, at first startup while it is not (affect probably windows too)
* It uses 100% CPU! even when disabling it
* It makes a black window appear first, then qtodotxt. This is very strange....

**Comment by PKEv** [comment]
ok, i try correct it behavior...

**Comment by oroulet** [comment]
btw it is singleton with an extra "n". There is a spelling error in settings

**Comment by PKEv** [comment]
tried to speed up the algorithm by optimizing and reducing the number of readings of settings, the result is not very clear ...
As I understand the decision making multi platform application without reading and locking the file is not present, and because of it there is a delay start

**Comment by PKEv** [comment]
That you think about it?

**Comment by oroulet** [comment]
Hi,
Running the applications still takes 100% CPU on ubuntu linux. It is not a startup issue, it uses all CPU all the time it is running.
I also think this is a lot of code for something which is usually handled by the window manager on Linux and Mac (It is the default in gnome3 at least). Maybe we should only call it and display option on windows. and move code out of app.py

**Comment by PKEv** [comment]
@oroulet please test
I exclude a regular examination of the disc and using a Qt function for tracking, but it does not work quite as expected, not sure that everything will be fine in Linux

**Comment by PKEv** [comment]
don't merge, i will try do it more simple, now I need your approval

**Comment by PKEv** [comment]
continued in #320

**Pull request closed without merging**
