### PR TITLE
Support for multiline tasks

### PR DESCRIPTION
**Pull request by tjaehnel**
This is an unofficial extension to todo.txt allowing to insert separators into the task which are displayed as newlines.
There is no change in the syntax of the task nor are there any additional newlines in the todo.txt file so it's still fully backwards compatible. It is only about interpreting the special sequence ' \\\\ ' (space-backslash-backslash-space) as a separator.

This is reflected in QTodoTxt in such a way that it now has a Multiline task edit dialog which automatically inserts the mentioned separator. This functionality can be enabled/disabled using the "Preferences" menu.

This features might somehow be related to issue #101

### CODE REVIEW

**Comment by mNantern** [comment]
@tjaehnel I tried your PR this week and I have some questions about it:

1. When using the auto-complete priority, cursor is put at the left of the inserted priority instead of the right: |(A) instead of (A)|
2. You print "CANCEL" and "OK" instead of using a logger (and the log message could be a little more explicit)
3. With multiline support it's hard to create a task only with keyboard (enter does not work of course), you should add a shortcut to create a task  like CTRL+ enter
4. How do you make the distinction between multiple task creation and one task with line break? Batch tasks creation is a feature that was asked ( #63 ) and that I really want in QTT. Maybe for task creation we can enter line break (\\) and use enter as a task separator ?

That's a great addition to QTT, thank you !

**Comment by tjaehnel** [comment]
Hi @mNantern ,

thanks for your suggestions.
I've updated a few things.

> When using the auto-complete priority, cursor is put at the left of the inserted priority instead of the right: |(A) instead of (A)|

This should be fixed now. I discovered a similar problem in the original single line edit. After auto-completion the cursor was put at the end of the line rather then after the just inserted priority/context/project. I corrected this as well.

> You print "CANCEL" and "OK" instead of using a logger (and the log message could be a little more explicit)

These lines were mistakenly left there - I just deleted them.

> With multiline support it's hard to create a task only with keyboard (enter does not work of course), you should add a shortcut to create a task like CTRL+ enter

True, I had the same thought. But since I don't have too much time to get into both python and QT I didn't implement it at first. I've now made this working but don't know if I did it in a reasonable way.

> How do you make the distinction between multiple task creation and one task with line break? Batch tasks creation is a feature that was asked ( #63 ) and that I really want in QTT. Maybe for task creation we can enter line break (\) and use enter as a task separator ?

I haven't thought about this case, because I don't have any use for batch task creation. But I put a fair amount of comments and progress information into tasks, so this is why I added this multiline feature.

If you want batch task creation I have two suggestions which might also be combined:
1. Introduce a separate batch creation dialog box or add a checkbox to the creation windows which disables the multiline features temporarily. In this case, one line is a task and you can still manually add the \\\\ separator in the line if necessary.
2. Keep the multiline dialog as it is but introduce a task separator (e.g. a line only containing '---'). Then one can have multi line tasks and still tell the system where a new task starts.

Toby

**Comment by mNantern** [comment]
Hey thanks for the update it's almost good !

I just found two small bugs:
* when you enter a new line, autocomplete doesn't work at the first character of the new line. If you add a space it's working again.
* When you check the preference "Support multiline task" a message is always shown "Revert to saved file (and lose unsaved changes)?" even if you don't have any unsaved changes.

Thanks for the great contribution !

**Comment by tjaehnel** [comment]
Hi @mNantern 

> when you enter a new line, autocomplete doesn't work at the first character of the new line. If you add a space it's working again.

OK, I added newline to the list of separators.

> When you check the preference "Support multiline task" a message is always shown "Revert to saved file (and lose unsaved changes)?" even if you don't have any unsaved changes.

This message comes from the "revert" method which I use to reload the file.
I now implemented this is a slightly different way such that it simply prevents changing from or to multiline mode when there ARE unsaved changes.
It's not a perfect solution but should suit most people's needs. Feel free to change this if you want.

Toby

**Comment by tjaehnel** [comment]
Hi @mNantern 

I just discovered another problem the already exists in the original QTodoTxt version but has more impact with the multiline extension now:
 1. Select a Project or Category in the tree on the left which contains tasks 
 2. Edit one task
 3. Hold down CTRL (or Command on Mac) while clicking OK

The focus now jumps back to the "Pending" section on top.
If you just click OK (without holding CTRL) it stays in the category you selected before.

Can you reproduce this on your machine? Do you have any clue why this happens? 
I have no idea, but it is rather inconvenient if you finish task editing with CTRL+RETURN.

Toby

**Comment by mNantern** [comment]
Yep I can reproduce on your branch and on master. I never noticed that before...
I will try to look at it but it's effectively inconvenient.

Another thing I was thinking about it's that it's a little "ugly" to have all that white space between your text and the autocomplete:

image1

We can have an auto-grow on that box. Something like that:
image2
image3

I made 2 commits for that : https://github.com/mNantern/QTodoTxt/commits/multiline

What do you think about that ? It needs a little more work (for example we don't need to remember the last size of the popup) and I'm not sure that I can do that soon

**Comment by tjaehnel** [comment]
Hi @mNantern 

I'm still there. Sorry for the delay I'm rather busy and only have very few time to work on this.

I made some changes regarding the auto-resize, but I'm not sure if you like it.

You are definitely right that the vertical space between the cursor and the autocompletion does not look nice. On the other hand there are a few things I find a bit awkward about the auto-resize such as:
* I like to always have a minimum number of lines shown in the window such that I recognise I can enter more than one line.
* When I remove lines, the box shrinks, but the window does not
* Manually resizing the window also keeps the box at a fixed height
I tried to fix some of these things, but this again results in some amount of space.

Also if I insert some project or context in a line other than the last one, the autocomplete still appears at the bottom.

So I guess the most effective solution for this would be an overlay pop-up on the text at the cursor position. But I don't know how to do this.

Anyway, for my use I don't bother too much about that additional space.
What bugs me more is the problem that CTRL-Enter moves me out of the currently selected section but I can't find a solution for this.

Toby

**Comment by tjaehnel** [comment]
OK, I think I fixed it.
When I hold down CTRL QTreeWidget switches into multi selection mode.
Since according to the API documentation QTreeWidget.setCurrentItem automatically selects the given item, it seems one should not manually select the item before.

**Comment by mNantern** [comment]
Sorry for the delay, I've been rather busy myself.

Can you rebase your PR so I can test it ? (Something like that : https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)

Thank you !

**Comment by funkyfuture** [comment]
@tjaehnel there's an interesting proposal in #63 that fits to this feature. do you think you can add this functionality?

**Comment by tjaehnel** [comment]
@mNantern I rebased the PR - did a squash as they suggested in the tutorial, hope this is OK, otherwise I can redo it without squashing.
Thh, the Tracis CI reports a failure but I don't see what's the problem...

@funkyfuture Batch-creation as suggested in #63 is a bit contrary to the multiline feature but still doable (see my comment with suggestions from 7th Jan above)
I don't have any personal use for batch creation, so I leave this implementation to someone else. ;-)

**Comment by funkyfuture** [comment]
before i do a review can you please:
- write a short documentation that explains the users this feature
- give me hints where else this 'unofficial extension' is implemented

btw, it's easier to test features when they are in a dedicated branch.

i can also see that you introduce a lot of changes to the backend-modules, which will provoke conflicts with my rework of the [`Task`-class](https://github.com/funkyfuture/QTodoTxt/tree/lib-task); and looking at your extensions of the `settings`-module confirms my urge to remodel that as well. it's certainly not your fault that work on that stalled, but i'd tend to merge this before any new-feature-related library changes.

**Comment by tjaehnel** [comment]
Hi @funkyfuture 
> write a short documentation that explains the users this feature
Could you please point me to a place, where I could add it, such that everything is in one place and has the same structure?
> give me hints where else this 'unofficial extension' is implemented
Nowhere
> btw, it's easier to test features when they are in a dedicated branch.
Yes, I used a dedicated fork for this
I was anyway a bit surprised how these pull requests work, because I haven't used them before.
Still, everything is in one branch.
> [...] i'd tend to merge this before any new-feature-related library changes.
That's fine.
Thanks for informing me. I had some ideas for the design of the Task class as well and it seems you already fixed that. That perfect, how is the status on this?

**Comment by funkyfuture** [comment]
> Could you please point me to a place, where I could add it, such that everything is in one place and has the same structure?

eventually it belongs into the wiki. however until it's merged, just post it in the PR here as markdown.

>> give me hints where else this 'unofficial extension' is implemented

> Nowhere

in these regards, could you please:

- research whether something similiar was ever proposed
- propose this extension to the official/reference todo.txt-implementation

as i'm really not fond of cluttered standards. (see all the markdown-offsprings, so sad.)

and a new issue: as i rebased the master-branch, this PR is split into many commits again. sorry, but this  mess had to be solved. anyhow, i propose you fork my `lib-task`-branch and rebase against it.

it's current state is described here: https://github.com/mNantern/QTodoTxt/issues/94#issuecomment-69645263

i have the suspicion that i made a mistake with the filters. yet there's still some work until i fixed and rebased against master. i hope to get this done until Monday and will notice you then.

**Comment by funkyfuture** [comment]
i pushed my current wip. but there are still some issues left, most hindering the non-rendering. you can fetch that branch and base a branch for your feature on that. you can later rebase again when my branch is updated.

i also thought about this feature and its conflict with a batch creation, imo the way to deal with that would be to:
- add a subtle 'modeswitch'-button to the taskedit-widget
- default that to batch-creation, because that's an expected behaviour if you are a not aware of an unofficial extension
- add a config-option to change that default

**Comment by kmic2006** [comment]
I'm a little bit unhappy with the suggested change. First of all, I would find it extremly useful to have line wrapping in both the task view and the task edit (I therefore don't understand, why issue #101 was closed, by the way). But I don't see the need for introducing a _manual_ line wrap option here. Why not just doing a dynamic / virtual line wrap, when the text to display is longer than the available space? The second thing is, that the current implementation of the multiline edit still has some technical problems, see comment from 13 Mar. Up to now, I would suggest not to merge the proposed changes to the master branch. But maybe rewriting of the proposed code would change the situation.

**Comment by kmicc** [comment]
I just figured out that the introduction of the special line separator sequence ``` \\``` by @tjaehnel was completely unnecessary. 

The tasks in QTodoTxt are displayed with a QLabel with enabled rich text functionality. This means: You can use *any* of the supported HTML subset (see http://doc.qt.io/qt-4.8/richtext-html-subset.html) to format your tasks (just try ```<b>Hello</b> <i>Qt!</i>``` as a task description). I wasn't aware of this but that's a really cool feature! (Additionally, using HTML-Tags is fully compliant with the todo.txt format definition.)

What tjaehnel suggests in this pull request, can simply be done by inserting ```<br />``` to the task description. In the current implementation doing so will display only the first line, as there is no multiline support. With https://github.com/kmicc/QTodoTxt, which has multiline support implemented (at least for the tasks view), it works fine.

In this pull request was furthermore suggested to add multiline support for the task *editor*. I'm going to work on this feature too and hopefully I can reuse some of the parts of this pull request.

**Comment by kmicc** [comment]
I will try to get this thing working.

**Comment by oroulet** [comment]
closing, nobody seems interested to work on this, and I think it would be better to remove these dialogs and do the editing directly in TaskList

**Pull request closed without merging**
