### PR TITLE
multiline editor

### PR DESCRIPTION
**Pull request by oroulet**
probably small bugs left but the basis is working and completer is much nicer

fixes: https://github.com/QTodoTxt/QTodoTxt/issues/289 , https://github.com/QTodoTxt/QTodoTxt/issues/101 

@PKEv

### CODE REVIEW

**Comment by PKEv** [comment]
It works great, but it works well only in the presence of gaps in the text, otherwise the text is not tolerated

**Comment by oroulet** [comment]
What do you mean? What kind of task is not supported?

**Comment by oroulet** [comment]
And what error happens? Stack Trace

**Comment by PKEv** [comment]
Errors do not occur, I mean that the text has no gaps are not transferred to the new line

**Pull request merged**
