### PR TITLE
remove custom settings, add setup.py, add Edit button, add AllTasks filter and remember filter on close

### PR DESCRIPTION
**Pull request by oroulet**
fixed conflict.
I am thinking to merge this soon if nobody has good arguments against

### CODE REVIEW

**Comment by kmicc** [comment]
Remark: This PR replaces PR #186.

**Comment by kmicc** [comment]
Thank you for that large contribution. Maybe first some organisational things: If I'm right, this pull request contains several more or less unrelated things:
* Completely remove use of custom settings (#179): 7939c38, d700452
* Add setup.py and upload to pip (#180): dfb0d19, dbac220
* Add edit action in toolbar and menu (#174): 4abdb9b, 3a62e8c
* Add AllTasks filter: 012a943
* Remember last selected filter on close: c0ffb84

Mixing all these things together in one pull request makes it extremly hard for me (and probably also for other people) to review your proposed changes. Would it be therefore possible for you to:
a) Create separate branches containing only commits that belong logically together, even if such a branch consists only of a single commit (see my list above). (You can cherry-pick the corresponding commits.)
b) Push all these branches to the QTodoTxt repository. 
c) Create pull requests for all the branches pushed to the main repository.

a) and c) would really simplify reviewing and discussing proposed changes. b) and c) would allow team members to add additional commits in a very simple way to a pull request, if needed (for example minor bugfixes or similar things).

I suppose you would have to use your local git installation to perform the proposed steps. If that's a problem for you, just let me know. Maybe I can help you, or we have to find another solution.

**Comment by oroulet** [comment]
There are several things yes but every commit is only doing one clear thing apart from one bug fix. If you really cannot understand the changes and promise to look at it quickly I can split the PR.

**Comment by kmicc** [comment]
I will have a look as far as it is possible for me.

**Comment by kmicc** [comment]
I've just splitted it up (using a quite amount of git magic). Hope it won't get too complicated. More to come tomorrow.

**Pull request closed without merging**
