### PR TITLE
fix and improve autocomplete

### PR DESCRIPTION
**Pull request by oroulet**

### CODE REVIEW

**Comment by oroulet** [comment]
@kmicc you should cherry.pick that one to your 1.5 branch

**Comment by oroulet** [comment]
@kmicc can you have a quick look at those PR. I am getting crazy at maintaining so many different branches. I woud like to merge them and clean my repository.

**Comment by oroulet** [comment]
and here we have conflicts.... expected when we have so many branches pending... trying to fix them

**Comment by kmicc** [comment]
ff97501 (partly) included to 1.5 branch.

**Comment by oroulet** [comment]
merging. many fixes needed in master

**Pull request merged**
