### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by PKEv**
must help only if python ver. < 3.5

in my case python v.3.5 compile don't work  - error no file "run_w-py3.5-win-amd64.exe"

### CODE REVIEW

**Comment by PKEv** [comment]
#378

**Comment by oroulet** [comment]
Great to see you back @PKEv !

**Comment by PKEv** [comment]
These changes I think it is not necessary to combine, I just wanted to show in which direction should continue to move, probably have to move to a different build system and abandon the py2exe

I am also happy to be back but not enough time

**Comment by oroulet** [comment]
I let you fix the tests, then I or you can merge. No issue here

**Comment by anacondaqq** [comment]
thank you very much for fix. Works pretty well (tested many features, and works fine, but maybe i something miss, anyway still pretty stable).

 
Here is a link for 1.7.0 windows version build (builded with ISS script). 

## Download 
#### [mega](https://mega.nz/#!85IC1CrY!o7oeKkn1F3_ucYbGFFD4_O4nTvCM2vX6ASM8VJ6hGOA) 14.44MB size
#### [dropbox](https://www.dropbox.com/s/mamhors0j171omk/qtodotxt_1.7.0.exe?dl=0) 14.44MB size

## Technical Details

Latest master hash: f3fdc99c2a0e7959c0376e3691aa4d264fd0259b + merged current PR
While building - no errors or warnings. Pretty fine works. All what have i did -> it's i changed numbers of old 1.6.1 version in iss script to actual 1.7.0

Tested on Win10 x64 v1607

Thx again 👍

**Comment by PKEv** [comment]
need to make changes to avoid problems with the release distributions in the future

**Pull request merged**
