### PR TITLE
Simplify and improve performance of Tasks, and move all task tests to unittest

### PR DESCRIPTION
**Pull request by oroulet**
new attempt.
All attributes of Task are now all read only. Task should only be modified through special methods such as setComplete(), although the Python language does not enforce it.
Less cool but more efficient as editing of task is rare while filtering/sorting happens all the time.
It is also much less code.
Also added many tests for Task class

### CODE REVIEW

**Comment by oroulet** [comment]
@kmicc can you have a look? I am confident these changes are correct. I do not have anything more I want to do for the Task class. Next will be to look at filters. funkyfuture had some changes I want to look at. But everything is depending on the new Task class so I need to get it merged.

**Comment by kmicc** [comment]
Had only little time for QTT this week. Will have a look today or tomorrow.

**Comment by kmicc** [comment]
Good news. Couldn't find any big issues. Especially the priority stuff seems to work as expected. 
Two minor things:
- The date format YYYY-MM isn't marked as invalid anymore for due-, creation- and completion-dates (t-dates in this format are still marked as invalid), but using this format doesn't work. I think we should enforce the format YYYY-MM-DD and print out a warning as before, if it isn't used.
- Change dialog text from "Toggle Complete for ..." to "Toggle completeness of ...". I'm not a native speaker, but the later version seems to be more correct to me.

**Comment by oroulet** [comment]
> Couldn't find any big issues.

Good

> we should enforce the format YYYY-MM-DD and print out a warning as before, if it isn't used.

This is a consequence of not parsing dates everywhere. A warning is printed on stdout when parsing at startup. It is possible to re-implement the old behaviour by adding a new flag like bad_due_date, but extra code has a cost and I am not sure how important this is. Users see that there is an issue since the date is not highlighted.

> Change dialog text from "Toggle Complete for ..." to "Toggle completeness of ...".

Good point

**Comment by kmicc** [comment]
> This is a consequence of not parsing dates everywhere. 

Could you please have a look to task_htmlizer.py, line 64? It seems to me that parsing (accidently?) is still done there.

> A warning is printed on stdout when parsing at startup. 

Yes, I saw it, but 90% of the users won't see them because they don't start QTT from the command line.

> It is possible to re-implement the old behaviour by adding a new flag like bad_due_date, but extra code has a cost and I am not sure how important this is. 

Whats about two new members for the Task class: a bool parserError and a string parserErrorString (in parserErrorString multiple error messages can be concatenated). In task_htmlizer both can be evaluated and the parserErrorString is added to the end of the task, if parserError == True. A similiar syntax check could be done done in the TaskEditor too. If you want, I can try to provide an implementation for this (in a later PR maybe, so we don't need to stop this PR).

> Users see that there is an issue since the date is not highlighted.

That's correct, but a little bit more visible error message could be useful.

**Comment by kmicc** [comment]
Could you also please cherry-pick https://github.com/kmicc/QTodoTxt/commit/d69ca89bc ?

**Comment by oroulet** [comment]
fixed everything you mentioned. Hopefully did not break anything

**Comment by oroulet** [comment]
but your commit break tests :-)

**Comment by kmicc** [comment]
See https://github.com/oroulet/QTodoTxt/pull/3 for some additional changes. No further issues for me with this PR.

**Comment by kmicc** [comment]
Thanks for your work!

**Pull request merged**
