### PR TITLE
All tasks filter

### PR DESCRIPTION
**Pull request by kmicc**
Taken from #187.

### CODE REVIEW

**Comment by oroulet** [comment]
noe galt med den. Den inneholder alt for mange commit

**Comment by oroulet** [comment]
Something wrong here. Too many commits in this pr

**Comment by kmicc** [comment]
Yes, only the last two commits actually belong to this pull request. But they depend on some of the other commits, so a clean splitting wasn't possible without too much pain. After the relevant other pr are merged, we can rebase the branch of this pr and everything should (hopefully) be ok.

**Comment by kmicc** [comment]
You are right. Simplified things a little bit more. Only the commits beginning with e326d49 belong to this pull request. These depend (partly) on #189, so a clean splitting is not possible. After merging #189, we can rebase the branch of this pr and everything should be ok.

**Comment by oroulet** [comment]
>>  In this state, this feature is quite useless for me. :-(
maybe but it implements the necessary infrastructure so it should be easy to add the dynamic filters. So I propose to merge it as soon as we fix the QSettings thing

**Comment by kmicc** [comment]
I would prefer merging a complete feature. Anyway, we have to wait for #189.

**Comment by kmicc** [comment]
There are still two open issues. Why did you merged?

**Comment by oroulet** [comment]
Sorry I understood it was OK to merge since qsettings stuff is merged. What
were the issues?

**Comment by kmicc** [comment]
Created issues for that. I wrote it in a comment but I don't know where it has gone (Maybe it was a commit-related comment and github deleted it when I rebased the branch?).

**Pull request merged**
