### PR TITLE
improve task interface

### PR DESCRIPTION
**Pull request by oroulet**
inspired from funkyfuture patch
not really happy with how complex Priority class is but at least the Task interface is now better
task.priority += 1
I could not split this PR

### CODE REVIEW

**Comment by kmicc** [comment]
I like the changes, they look really good.
> I could not split this PR

Absolutely no problem here.

Commit 4fd6afd: Unfortunately you made some oversimplifications and also introduced one bug concerning QSettings. I think that was my fault because I missed to comment my code so it was really not easy to understand why some things had to be written as they were. I will comment the issues directly in the commit and also provide a patch.

Commit d30835c: I'm in no way a test expert, but removing the test for one of the central functions in QTT without an adequate replacement seems no a good idea for me.

Commit d4ac5cc: Why do we need a fourth command for invoking tests? Could that not be included to the command `py.test qtodotxt/test`?

**Comment by oroulet** [comment]
>> but removing the test for one of the central functions in QTT without an adequate replacement seems no a good idea for me.

There was allready a replacement written but disabled. I enabled them. But I see some tests are missing and I will add them to the new test file

>> Why do we need a fourth command for invoking tests? Could that not be included to the command py.test qtodotxt/test?

My fault. I did not understand how that workedt. I will fix this

**Comment by oroulet** [comment]
>> There was allready a replacement written but disabled. I enabled them. But I see some tests are missing and I will add them to the new test file

I just fixed the tests and found out that everything I could see is already tested. The removed tests are now redoundant

**Comment by kmicc** [comment]
There are two errors in your code:
a) Decreasing priority of task `(A) test` *once* leads directly to `test` instead of `(B) test`.
b) The current tests doesn't catch this, but the (removed) doctest would have catched it (in test 10). So your statement "The removed tests are now redundant" is wrong.

Fix for b) provided in https://github.com/oroulet/QTodoTxt/pull/2

**Comment by oroulet** [comment]
a) Decreasing priority of task (A) test once leads directly to test instead of (B) test.
OK thanks, I will have a look
b) see comment in PR. I will add the missing tests. I think the current tests do not catch all cases anyway so I will add a bunch of tests to test_tasks.py.

**Comment by oroulet** [comment]
fixed a) and added tests for priority. Still need to port a few extra tests

**Comment by oroulet** [comment]
Can we merge that one now? I merged as much as I could from your PR. I want to write more tests and improve further Task class but work will depending on this one and it would be clearer to not do everything in one PR

**Comment by oroulet** [comment]
closing this request. I though about it and I think changes are wrong. priority += 1 is cool but not efficient.
I will cherry-pick interresting changes form this request and make a new PR.

**Pull request closed without merging**
