### PR TITLE
memory leak

### PR DESCRIPTION
**Pull request by PKEv**

### CODE REVIEW

**Comment by oroulet** [comment]
I have never seen that call before. Are we supposed to always use it with pyqt5?

**Comment by PKEv** [comment]
http://stackoverflow.com/questions/20164015/is-deletelater-necessary-in-pyqt-pyside

**Comment by PKEv** [comment]
I'm not good in python and pyqt...

**Comment by oroulet** [comment]
And qtodotxt is not a good example... The original author forced a style
which qt is not made to follow...

**Comment by PKEv** [comment]
yes, style really interesting..

**Pull request merged**
