### PR TITLE
remove custom settings, add setup.py, add Edit button, add AllTasks filter and remember filter on close

### PR DESCRIPTION
**Pull request by oroulet**
This removes many potential bug and will facilitate system installation

### CODE REVIEW

**Comment by oroulet** [comment]
currently broken. will fix it

**Comment by oroulet** [comment]
Now it works

**Comment by oroulet** [comment]
but it is difficult to know whithout tests.... I someone undertsnading travis could fix tests...

**Comment by oroulet** [comment]
added setup.py and uploaded beta version to pip

sudo pip3 install qtodotxt --pre

**Comment by oroulet** [comment]
@kmicc @mNantern can you have a look and see if I did not break anything?
And also look at content of setup.py, might be missing things you want

**Comment by kmicc** [comment]
Thanks for addressing this issue. Will have a look in the next few days.

**Comment by oroulet** [comment]
closing to solve conflics

**Comment by kmicc** [comment]
Would rebasing the branch to the current master not have solved the "conflict" too?

**Comment by oroulet** [comment]
No I tried

**Pull request closed without merging**
