### PR TITLE
change_the_display_of_links

### PR DESCRIPTION
**Pull request by PKEv**
instead of referring only displays the file name or the name of the domain on the Internet

file:///C:/film1.avi -> film1.avi
http://rutracker.org/forum/index.php -> http://rutracker.org/

### CODE REVIEW

**Comment by PKEv** [comment]
if normal then I will correct tests

**Comment by oroulet** [comment]
What about having '...' before to show it has been truncated? Just an idea

**Comment by PKEv** [comment]
like this?
http://rutracker.org/forum/index.php -> http://rutracker.org/...

**Comment by oroulet** [comment]
No. Maybe http://server/.../myfile.txt or http://.../myfile.txt or maybe
only .../my file.txt

Last one is shortest

**Comment by PKEv** [comment]
here it is necessary to consider two options for local files and Internet
in most cases on the Internet page name is not important, interesting domain
and to local files on the contrary

given the complexity of each time to assess the length of the line, and for uniformity


file:///C:/film1.avi -> ../film1.avi
http://rutracker.org/forum/index.php -> http://rutracker.org/...

**Comment by oroulet** [comment]
Ok

**Comment by PKEv** [comment]
please test

**Pull request merged**
