### PR TITLE
inline editor and cleanup og task editor

### PR DESCRIPTION
**Pull request by oroulet**
phase 1: restructure taskeditor to be a normal dialog
phase 2: use model/view classes to get more flexibility
phase 3: inline editor

This changes not make it also possible to develop new feature like splitting the list view lines to allow ordering by something else than the harcoded order.

Ready for testing, if anybody has time

### CODE REVIEW

**Comment by oroulet** [comment]
@PKEv I made it! almost. But as you see in screenshot, the style is wrong. Maybe you have some ideas?
The drawing code is there:  https://github.com/QTodoTxt/QTodoTxt/pull/381/files#diff-f3001d11db0da546691bca47775f12caR170

screenshot from 2017-01-14 20-45-25

**Comment by oroulet** [comment]
@PKEv I made it! almost. But as you see in screenshot, the style is wrong. Maybe you have some ideas?
The drawing code is there:  https://github.com/QTodoTxt/QTodoTxt/pull/381/files#diff-f3001d11db0da546691bca47775f12caR170

**Comment by PKEv** [comment]
when select text in inline edit it looks like damaged
probably what that race font size

**Comment by oroulet** [comment]
@PKEv maybe last commit fixed it? It looks perfect on my screen (black orange theme)

**Comment by PKEv** [comment]
no, qedit is smaller and all letters like 'y' 'q' 'p' 'g' are cut from the bottom

**Comment by oroulet** [comment]
OK I see it. Will try to have a look. Thanks for testing!

**Comment by oroulet** [comment]
taking a chance and merging that one

**Pull request merged**
