### PR TITLE
[patch] "ValueError: month must be in 1..12"

### PR DESCRIPTION
**Pull request by sdenel**
Avoid error:
    ValueError: month must be in 1..12
Solution from: http://stackoverflow.com/a/23447523

### CODE REVIEW

**Comment by bartgenuit** [comment]
Thanks, I had the same issue. 
However, I would propose to use
'''
... % 12
'''
(modulo 12) for simplicity. I will try to build a pull request on yours, if you don't mind.

**Comment by sdenel** [comment]
Dear Bartgenuit,

I thought about using a modulo: but correct me if I'm wrong, this would not update the year as expected in December.

**Comment by bartgenuit** [comment]
Thanks for the reply. You're right, I didn't think about that. :)

And I cannot think of another way to make it more elegant, apart from using a more elaborate library such as dateutil. Which is a bit over the top here.

So I +1 your fix

**Comment by kmicc** [comment]
Thanks for providing a fix that fast. Merged into https://github.com/kmicc/QTodoTxt.

**Comment by bartgenuit** [comment]
@oroulet, this should fix the 'december bug'..

**Pull request merged**
