### PR TITLE
make flake8 happy

### PR DESCRIPTION
**Pull request by oroulet**

### CODE REVIEW

**Comment by oroulet** [comment]
finally, now is travis happy. Can I merge it?

**Comment by kmicc** [comment]
What does the option `--max-complexity 13` for flake8 do? If it's important, it should be added to `CONTRIBUTING.md` too.

**Comment by oroulet** [comment]
Default complexity is 10 but two methods had 11 and 12 so I added this flag
to make flake happy. I am not sure what to do next. We could split methods
by I think the complexity computation is flawed, sometimes it flags simple
methods as complex....

**Comment by kmicc** [comment]
Ok, no problem. And thanks for cleaning that stuff here.

**Pull request merged**
