### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by PKEv**
Added the ability to localize
Of course even sure there are places that are not translated, but all at once you will not find
#143

### CODE REVIEW

**Comment by oroulet** [comment]
I know nothing about translation so I can only trust you

**Comment by anacondaqq** [comment]
hi, how to use it?

**Comment by oroulet** [comment]
good point. We need to document it somewhere for developer and translators.
Maybe in README?

**Comment by PKEv** [comment]
@anacondaqq  Right now, just load transfer according to your system locale - if it is not found it will not boot

**Comment by PKEv** [comment]
@anacondaqq look #332

**Pull request merged**
