### PR TITLE
fix link of closed tasks, link to local path, simplify htmlizer and remove extra parsing

### PR DESCRIPTION
**Pull request by oroulet**
also fixes https://github.com/QTodoTxt/QTodoTxt/issues/227
and https://github.com/QTodoTxt/QTodoTxt/issues/139
and correctly parse creation date if it exists

### CODE REVIEW

**Comment by kmicc** [comment]
The first 5 commits are duplicates to #226 if I'm not wrong?

**Comment by oroulet** [comment]
Yes, I was hoping #226 got merged soon so they disappear here

**Comment by oroulet** [comment]
now we have only one commit

**Comment by oroulet** [comment]
merging, 5 days out and no complains

**Pull request merged**
