### PR TITLE
Optional time in dates

### PR DESCRIPTION
**Pull request by ethingelstad**
This is the code I wrote before creating issue #372.
- Switch due and threshold from date to datetime.
- Change formatting code to show datetime without a time component as before.

### CODE REVIEW

**Comment by ethingelstad** [comment]
Next steps are:
- Update error messages
- Write tests
- Some kind of update mechanism so that when time gets past a due or threshold time, the line shows up in the list. Currently, this seems to only happen when I restart the program. I have probably missed a detail somewhere.
- Anything else?

**Comment by oroulet** [comment]
this is more invasive than I imagined. The first thing to is fix your code to pass curent tests, then we need to make new tests for all corner cases with time at 0:00 etc...

**Comment by oroulet** [comment]
Looks much better!

**Comment by ethingelstad** [comment]
Thanks. First try was quick and dirty. Just about seeing if it looked like I could make it work. A bit of honest feedback got me thinking about how to do it better.
Tip: If Python 2 is the default (Ubuntu has this), you need to run tests with `py.test-3 qtodotxt/test`

**Comment by ethingelstad** [comment]
And now how to get my task to show up when the threshold time is reached. Actually, version 1.7.0 expects me to close QTodoTxt every night and open it again the next morning. If I leave it open until tomorrow, the tasks with threshold tomorrow would still be hidden.
The key seems to be Task.parseLine which is only called when a file is read (creates the object) and when a task is edited. We need to call parseLine for every line with a threshold or due date at least every midnight. The easiest is probably to just reparse the whole list at some interval. The interval could be a combo box in the preferences dialog (Never, Midnight, Every hour, Every five minutes).
I'm not sure if a reparse could cause problems if I edit something at the same time, though.
Any thoughts on this?

**Comment by oroulet** [comment]
Hi,
2 things:
* from what I understand of you code you decide that not having any time is the same as having 0:00 as time. Is this a correct assumption? I do not have time to look at this in detail, but I want to make sure that you have thought about it
* This refresh stuff is interresting, and we have another PR https://github.com/QTodoTxt/QTodoTxt/pull/370 that require the same kind of things. I think a good solution would be to support timed events, and I see two ways to do it:
* used python3 builtin solution: asyncio. we can start an asyncio loop in __init__ and close it closeEvent(). Then we can post things there like timers, coroutines, etc...
* Make something similar using QTimer. (Maybe easier but I am unsure about performance=
Anyway the solution will be that we add a timer member to Task, when parsing a task if we have a due date or if it is recurring, we start a timer, in the timer callback we force the reparsing of the task or create a new task if it is recurring. And of course in the reparsing we stop any existing timer.

I am not sure about the expected behaviout of a recurring task. Should we create a new task at timeout? or should we simply re-enable the task if was marked as done? If we create a new task than we have to decide how to handle several existing instances of one task @topas-rec

**Comment by ethingelstad** [comment]
Yes, I consider 2016-12-06 and 2016-12-06T00:00 to be the same. I found the implementation [here](http://stackoverflow.com/questions/1937622/convert-date-to-datetime-in-python#1937636).
Python has no built-in conversion from date to datetime. But this is at least how C# (Remarks section [here](https://msdn.microsoft.com/en-us/library/xcfzdy4x(v=vs.110).aspx)), Excel and Calc works.

**Comment by ethingelstad** [comment]
Scheduling reparsing for each task separately looks like a good solution. Remember it should be for both due and threshold, but that doesn't change the principle.
It seems like you have a plan, and I like it. I have never used asyncio or QTimer, so I can't tell you which is best.
Editing should probably set an internal flag in the task that the timer checks. If editing is active when a timer fires, the timer just stops itself and does nothing because it is going to be invalid soon. When the editing finishes, any existing timers are cancelled, the new text is parsed and new timers are set.
If the editing is cancelled, we should reparse the original text in case something changed while editing, but there is no need to change any timers.

**Comment by oroulet** [comment]
@ethingelstad i may have ideas but time is missing :-( and I dot really have use for that kind of thing..

**Comment by ethingelstad** [comment]
I respect that. There are always priorities. But thanks for merging what I did so far! For now I can just reload now and then. And I will at least have a look at implementing timers.

**Comment by topas-rec** [comment]
I need to have a more detailed look on this to understand your suggestion @oroulet. I'll comment when I'm done.

**Pull request merged**
